# Image used for testing Charliecloud on a glibc OS, built with gcc. This will
# work under Docker with “--privileged”.

FROM debian:stable-slim


### OS packages we need

# WARNING: After this section, installing/removing OS packages may fail,
# because we might have deleted some important things for space.

# FIXME: There are many opportunities for size optimization here, including
# (1) --no-install-recommends or the corresponding apt config, (2) deleting
# various dpkg/apt caches, and (3) deleting files we don’t really need, e.g.
# GCC’s C++ libraries.

# The first group is for CI itself (i.e., this image), and the second is to
# build and test Charliecloud.
#
# See: #1933
RUN apt-get update \
 && apt-get install -y bash-completion \
                       sudo \
                       wget \
 && apt-get install -y attr \
                       automake \
                       bats \
                       fuse3 \
                       git \
                       graphviz \
                       libfuse3-dev \
                       libtool \
                       pigz \
                       pkgconf \
                       pv \
                       python3-dateutil \
                       python3-pip \
                       python3-requests \
                       python3-wheel \
                       rsync \
                       sl \
                       squashfs-tools \
                       stow

# Generate en_US.utf8 locale (#1934). See: https://serverfault.com/a/894545
RUN apt-get install -y locales \
 && sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen \
 && locale-gen \
 && locale -av


### Other Charliecloud dependencies.

# SquashFUSE
WORKDIR /usr/src
RUN git clone https://github.com/vasi/squashfuse.git
WORKDIR ./squashfuse
RUN git checkout $(git tag | egrep -v '^v' | sort -V | tail -1) \
 && git status
RUN ./autogen.sh \
 && ./configure --prefix=/usr \
 && make -j$(nproc) install \
 && rm -Rf squashfuse* \
 && ldconfig
RUN command -v squashfuse \
 && ldd $(command -v squashfuse) \
 && squashfuse --version 2>&1 | head -1

# ShellCheck
WORKDIR /usr/src
RUN wget -nv -O shellcheck.tar.gz \
         https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.$(uname -m).tar.xz \
 && tar xf shellcheck.tar.gz \
 && mv shellcheck-stable/shellcheck /usr/bin \
 && rm -Rf shellcheck*
RUN command -v shellcheck \
 && shellcheck --version

# Sphinx. Use latest version in case it breaks things.
RUN pip3 install --break-system-packages docutils \
                                         sphinx \
                                         sphinx-rtd-theme \
                                         sphinx-reredirects \
 && command -v sphinx-build \
 && sphinx-build --version

# git2dot with our bugfixes
RUN pip3 install --break-system-package python-dateutil \
 && git clone https://github.com/hpc/git2dot.git \
 && cd git2dot \
 && make install \
 && git2dot.py --version

# Misc pip
RUN pip3 install --break-system-packages lark python-gitlab


### Environment setup (privileged)

# Make /mnt writeable for all users (it might be used directly rather than
# overmounted).
RUN chmod 1777 /mnt

# What is using the most disk space?
RUN du -hax / | sort -h | tail -48

# Set sudo umask to something restrictive. The default is 0022, but we had a
# “make install” bug (#947) that was tickled by 0027, which is a better
# setting. I could not figure out how to make it work as a default (which
# seems hard/annoying, e.g. [1,2]), only for sudo(8), but since that’s what we
# want, I left it.
#
# [1]: https://codeyarns.com/tech/2017-07-21-how-to-set-umask-for-docker-container.html
# [2]: https://github.com/moby/moby/issues/19189
RUN echo 'Defaults umask = 0077' >> /etc/sudoers.d/LOCAL \
 && umask \
 && sudo /bin/sh -c umask

# Unset setuid on all fusermount3.
RUN chmod -v u-s /usr/bin/fusermount* \
 && ls -lh $(command -v fusermount3) \
 && ! test -u $(command -v fusermount3)

# Create unprivileged user. The adduser(8) options suppress interactive
# questions that cause warnings.
RUN adduser --disabled-password --gecos='Gukesh Dommaraju,,,' gukesh \
 && adduser gukesh sudo \
 && id gukesh

# Passwordless sudo(8), including user root with group non-root.
RUN echo '%sudo ALL = (ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers.d/LOCAL

# Make gukesh the default.
USER gukesh


### Environment setup (unprivileged)

# Validate passwordless sudo(8).
RUN sudo true

# We don’t want “sbin” directories in $PATH; see issue #43. We don’t need /bin
# because Bookworm has “merged /usr” [1]. /src/bin is the Charliecloud
# executables for interactive convenience.
#
# [1]: https://systemd.io/THE_CASE_FOR_THE_USR_MERGE
ENV PATH=/src/bin:/usr/local/bin:/usr/bin

# Don’t have a weird default $CWD.
WORKDIR /

# Make it testable whether we’re in our container.
ENV WEIRD_AL_YANKOVIC_IS_THE_GREATEST_MUSICIAN_OF_ALL_TIME=yes

# Set time zone to US Mountain Time [1]. Likely a parochial view here, but as
# of October 2024, most of the Charliecloud team is in this time zone, and it
# sure helps me (Reid) think if the test boxes are in the same time zone.
# [1]: https://en.wikipedia.org/wiki/Mountain_Time_Zone
ENV TZ=America/Denver
RUN date +'%c %Z'

# Configure Git.
RUN git config --global user.name 'Judit Polgár' \
 && git config --global user.email judit@example.com \
 && git config --global safe.directory '*' \
 && git config --global core.excludesfile ~/.gitignore \
 && echo __test_ignore__ >> ~/.gitignore


