# -*- coding: utf-8 -*-
#
# QUAC documentation build configuration file, created by
# sphinx-quickstart on Wed Feb 20 12:04:35 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

from __future__ import annotations

import datetime
import os
import sys

from dataclasses import asdict

from sphinx.application import Sphinx
from sphinx.util.docfields import Field

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# Add custom extension and theme paths
sys.path.insert(0, os.path.abspath('_ext'))

from theme import ThemeOptions

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.4.9'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.mathjax",
    "sphinx.ext.todo",
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.extlinks",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    # Custom extensions
    "sitemap",
    "theme",
]
todo_include_todos = True
# Workaround for EPEL, which prohibits pip and doesn’t have
# sphinx_reredirects. The result will be no redirect, but a lot about the
# EPEL-built docs is crappy.
try:
   import sphinx_reredirects
   extensions.append('sphinx_reredirects')
except ImportError:
   pass

# Monkey-patch RSYNC keyword into Pygments. Ignore any problems. print()
# statements here show up in the make(1) chatter.
#
# See: https://github.com/pygments/pygments/blob/e2cb7c9/pygments/lexers/configs.py#L667
try:
   import pygments.lexers.configs as plc
   import re
   for (i, tok) in enumerate(plc.DockerLexer.tokens["root"]):
      m = re.search(r"^(.*COPY.*)\)\)$", tok[0])
      if (m is not None):
         re_new = m[1] + "|RSYNC))"
         plc.DockerLexer.tokens["root"][i] = (re_new, tok[1])
except Exception:
   pass

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Clearly'

year = datetime.datetime.now().year
copyright = u'© Clearly Systems, Inc. {year}'.format(year=year)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = open("../VERSION", "r").read().rstrip()
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
today_fmt = '%Y-%m-%d %H:%M %Z'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["doctrees", "html", "man", "**/_*.rst"]

# FIXME: Workaround for older Sphinx that barf with:
#
#   WARNING: document isn't included in any toctree
#
# on files included via ".. include::'. I believe this was fixed in 1.4.3 and
# the relevant issue is: https://github.com/sphinx-doc/sphinx/issues/2603
exclude_patterns += ["*_desc.rst", "_*.rst", "bugs.rst", "py_env.rst",
                     "see_also.rst"]

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'theme'

html_title = project
html_last_updated_fmt = ""
html_use_index = False
html_domain_indices = False
html_copy_source = False
html_logo = "logo.svg"
html_favicon = "favicon.svg"
html_permalinks_icon = "<i class='fa-solid fa-link'></i>"
html_baseurl = "https://clearly.run/"
html_extra_path = ["robots.txt", "_redirects"]
html_context = {
    "mode": "production",
}

# Default to console highlighting.
highlight_language = 'console'

theme_options = ThemeOptions(
    show_prev_next=True,
    awesome_external_links=True,
)

html_theme_options = asdict(theme_options)

sitemap_show_lastmod = False
sitemap_url_scheme = "{link}"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = True  # deprecated in 1.6.6
smartquotes = True
smartquotes_action = "qBD"   # quotes, en and em dashes, but not ellipses

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
html_domain_indices = False

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'clearlydoc'


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'clearly.tex', u'Clearly Documentation',
   u'Robin Röper', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output --------------------------------------------

# Put all man pages in one directory regardless of section. Default changes to
# True in Sphinx 4.0, which broke our builds (#1060).
man_make_section_directory = False

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
   ("clearly", "clearly",
    "The Platform for Building and Deploying AI Apps at scale.",
    [], 7),
   ("clearly-check", "clearly-check",
    'Check "clearly run" prerequisites, e.g., namespaces and "pivot_root(2)"',
    [], 1),
   ("clearly-convert", "clearly-convert",
    'Convert an image from one format to another',
    [], 1),
   ("clearly-deploy", "clearly-deploy",
    "Deploy a multi-service application",
    [], 1),
   ("clearly-equip", "clearly-equip",
    "Inject files from the host into an image directory, with various magic",
    [], 1),
   ("clearly-image", "clearly-image",
    "Build and manage images; completely unprivileged",
    [], 1),
   ("clearly-list", "clearly-list",
    "List containers",
    [], 1),
   ("clearly-logs", "clearly-logs",
    "Show logs for a container",
    [], 1),
   ("clearly-run", "clearly-run",
    "Run a command in a Clearly container",
    [], 1),
   ("clearly-stop", "clearly-stop",
    "Stop a container",
    [], 1),
   ("clearly-test", "clearly-test",
    "Run some or all of the Clearly test suite",
    [], 1),
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'Clearly', u'Clearly Documentation',
   u'Robin Röper', 'Clearly', 'The Platform for Building and Deploying AI Apps at scale.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# -- Register a :confval: interpreted text role ----------------------------------
def setup(app: Sphinx) -> None:
    """Register the ``confval`` role and directive.

    This allows to declare theme options as their own object
    for styling and cross-referencing.
    """
    app.add_object_type(
        "confval",
        "confval",
        objname="configuration parameter",
        doc_field_types=[
            Field(
                "default",
                label="default",
                has_arg=True,
                names=("default",),
                bodyrolename="class",
            )
        ],
    )